// Copyright 2026 Blink Labs Software
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package scls

import "testing"

func merkleLeaves(t *testing.T) []Hash {
	t.Helper()
	return []Hash{
		EntryDigest("utxo/v0", []byte{0x01, 0x02}, []byte{0x03, 0x04}), // A
		EntryDigest("utxo/v0", []byte{0x01, 0x03}, []byte{0x05}),       // B
		EntryDigest("utxo/v0", []byte{0x02, 0x00}, []byte{0x06}),       // C
		EntryDigest("utxo/v0", []byte{0x03, 0x00}, []byte{0x07}),       // D
	}
}

func TestMerkleRoots(t *testing.T) {
	leaves := merkleLeaves(t)
	testDefs := []struct {
		name     string
		count    int
		expected string
	}{
		// empty tree -> Blake2b-224("")
		{"empty", 0, "836cc68931c2e4e3e838602eca1902591d216837bafddfe6f0c8cb07"},
		// single leaf -> the leaf itself
		{"one", 1, "c9535b87a76815a7fef321f6e8c23fc215ba20433e802203607b871f"},
		// H(0x00 || A || B)
		{"two", 2, "7cb55d91ce9ab61848d854c13d3e796afeb379590a3f18ea6b3c6468"},
		// C promoted to depth 1, then H(0x00 || H(A,B) || C)
		{"three", 3, "6bce4bbcc1ecfcb7a8cba0351a5cda149f404aa57b08a218718eb844"},
		// H(0x00 || H(A,B) || H(C,D))
		{"four", 4, "61f4542182c577ab9471a9fb00d0a1dda75a0a06752bc1452fe5a190"},
	}
	for _, td := range testDefs {
		t.Run(td.name, func(t *testing.T) {
			var tree MerkleTree
			for _, l := range leaves[:td.count] {
				tree.Add(l)
			}
			if got := tree.Root(); got != hashFromHex(t, td.expected) {
				t.Fatalf("got %x, want %s", got, td.expected)
			}
		})
	}
}

// Root must not mutate state: calling it twice, or adding after Root, stays correct.
func TestMerkleRootIsIdempotent(t *testing.T) {
	leaves := merkleLeaves(t)
	var tree MerkleTree
	tree.Add(leaves[0])
	tree.Add(leaves[1])
	tree.Add(leaves[2])
	r1 := tree.Root()
	r2 := tree.Root()
	if r1 != r2 {
		t.Fatalf("Root not idempotent: %x vs %x", r1, r2)
	}
	tree.Add(leaves[3])
	if got := tree.Root(); got != hashFromHex(t, "61f4542182c577ab9471a9fb00d0a1dda75a0a06752bc1452fe5a190") {
		t.Fatalf("add-after-root broken: got %x", got)
	}
}

// Incremental result must match a simple recursive reference implementation.
func TestMerkleMatchesReference(t *testing.T) {
	var refBuild func(leaves []Hash) Hash
	refBuild = func(leaves []Hash) Hash {
		if len(leaves) == 0 {
			return EmptyRoot()
		}
		if len(leaves) == 1 {
			return leaves[0]
		}
		// split at the largest power of two < len (left subtree is full)
		split := 1
		for split*2 < len(leaves) {
			split *= 2
		}
		return nodeDigest(refBuild(leaves[:split]), refBuild(leaves[split:]))
	}
	var all []Hash
	for i := 0; i < 33; i++ {
		all = append(all, EntryDigest("ns", []byte{byte(i)}, []byte{byte(i)}))
	}
	for n := 0; n <= len(all); n++ {
		var tree MerkleTree
		for _, l := range all[:n] {
			tree.Add(l)
		}
		if got, want := tree.Root(), refBuild(all[:n]); got != want {
			t.Fatalf("n=%d: incremental %x != reference %x", n, got, want)
		}
	}
}

// Golden vectors generated by the Haskell reference implementation
// (merkle-tree-incremental, tweag/cardano-cls commit 98d912a; reproduced in
// cardano-scrawls src/hash/merkle.rs). Leaf = H(0x01 || "Test"), added n times.
func TestMerkleGoldenHaskellVectors(t *testing.T) {
	leaf := hashParts([]byte{domainSepLeaf}, []byte("Test"))
	golden := map[int]string{
		2: "d3af86eb3e383618180e9e5e67b458f351335462871682ee332e20f8",
		3: "37c91e733d32604abaf8ddff2b274f60e9b66a0311860ceddb5d43f4",
		4: "e291561d5aa6555c44991f28f70dccb86352a4cd505b894a7bf85c4c",
		5: "4aa703d6add1a49f1603328aa89db822122f174282c1637606c59f7c",
		7: "ff159b2b1d0c703bf65bb0ae36dac26420cab122cc09df37c28df3a5",
	}
	for n, want := range golden {
		var tree MerkleTree
		for i := 0; i < n; i++ {
			tree.Add(leaf)
		}
		if got := tree.Root(); got != hashFromHex(t, want) {
			t.Fatalf("n=%d: got %x, want %s", n, got, want)
		}
	}
}
